### ISSUE TITLE
Incorrect text?

### ISSUE THREAD

**Issue by amuradyan** [TigranOhanyan/chess-finder-backend#1]
What are you trading?

https://github.com/TigranOhanyan/chess-finder-backend/blob/fa9614bcbb0e05dfe11766461d339a910c46856e/src/main/scala/Main.scala#L39

https://github.com/TigranOhanyan/chess-finder-backend/blob/fa9614bcbb0e05dfe11766461d339a910c46856e/src/main/scala/Main.scala#L50

**Comment by TigranOhanyan** [comment]
Thank you for your note. There is no such a text any more.
